# (c) Andrew Wei

version: 2
jobs:
  build:
    working_directory: ~/pug-base-layout
    docker:
      - image: node:latest
    steps:
      - checkout
      - deploy:
          name: Publish to NPM
          command: |
            if [[ $(git describe --tags) =~ ^v[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" >> ~/.npmrc
              npm publish
              echo "Successfully published to NPM"
            else
              echo "Skipping publish because this is not a release"
            fi